name: CI

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: todo_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: 依存関係をインストール
        run: npm ci

      - name: DBのマイグレーションを実行
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: todo_db
        run: |
          # migrateコマンドが失敗しても止まらないように if-present をつけてるよ
          npm run migrate --if-present


      - name: テストを実行
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: todo_db
        run: npm run test:ci
